### ISSUE TITLE
Error in README. transaction.execute returns Result<u64, PostgresError>

### ISSUE THREAD

**Issue by sindreij** [SkylerLipthay/schemamama_postgres#1]
The examples in the README does not compile because transaction.execute returns Result<u64, PostgresError>, while up returns Result<(), PostgresError>.

``` rust
fn up(&self, transaction: &postgres::Transaction) -> Result<(), PostgresError> {
    transaction.execute("CREATE TABLE users (id BIGINT PRIMARY KEY);", &[])
}
```

The OK-part needs to be mapped to `()` for this to work.

**Comment by SkylerLipthay** [comment]
Thanks! Fixed in b6c14d3.
