### ISSUE TITLE
Upgrade to use schemamama 0.2

### ISSUE THREAD

**Issue by palfrey** [SkylerLipthay/schemamama_postgres#2]
(as per title)

**Comment by SkylerLipthay** [comment]
Hi! This was covered by 3a2bf2ac84f9a141d4147ff94740c99ec96d1f71 and released with `1.1`.  Make sure to modify your `Cargo.toml` to specify `1.1` or run `cargo update`.

Please reopen this issue if I'm misunderstanding you.

**Comment by palfrey** [comment]
Ah! I think I've finally understood this. The pattern I'm used to for "up to version A.B, but not A.(B+1)" is "<A.(B+1)" where as you've written it as "<=A.B", which I'd found rather confusing. Also, that schemamama_postgres appears to have a different versioning scheme to schemamama probably isn't helping me either, but hey.

I've just upgraded the relevant project to use schemamama 0.2, so thanks.

**Comment by SkylerLipthay** [comment]
You have a fair point regarding the versioning scheme desync. My opposition to doing that is twofold: 1) laziness; 2) it would impose extra work on any 3rd party crate maintainers (currently just `schemamama_rusqlite`, as far as I know).
